# 网站配置

# 导入主题
# https://github.com/cotes2020/jekyll-theme-chirpy
# https://github.com/NichtsHsu/nichtshsu.github.io
theme: jekyll-theme-chirpy

# 网页的语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果它与文件夹 `_data/locales`中的某个文件同名，则布局语言也将改变、
# 否则，布局语言将使用默认值 "en"。

lang: zh-CN

# 切换到您所在的时区 ' https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Wendell's blog   # the main title
# title: Wendell

tagline: 读书，买花，长大。   # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  Time will tell.

# 填写网站的协议和主机名。
# 例如，“https://username.github.io”，注意不是以“/”结尾。
url: 'https://XiaoWendell.github.io'

github:
  username: XiaoWendell             # change to your github username

# twitter:
# username:            # change to your twitter username

social:
  # 更改为您的全名。
  # 它将显示为帖子的默认作者，并在页脚显示为版权所有者
  name: Wendell
  email: wendell.wenwu.he@gmail.com           # change to your email address
  links:
    # 第一个元素作为版权所有者链接
    - https://github.com/XiaoWendell      # 更改为你的 Github 主页
    # - https://x.com/-     # 更改为你的 twitter主页
    
# 取消下面的注释，添加更多社交链接
    - https://www.zhihu.com/people/xiao-feng-75-38-5

    # - https://www.facebook.com/username

    # - https://www.linkedin.com/in/username

google_site_verification: "3PwulRbCal1wvD_pGnM8ew-hq3Vvzrb9MCuK8k9RP80"    # 填入验证字符串

webmaster_verifications:
  # https://search.google.com/search-console
  google: "3PwulRbCal1wvD_pGnM8ew-hq3Vvzrb9MCuK8k9RP80"

  # https://ziyuan.baidu.com/linksubmit/index
  baidu: "codeva-7TczltvchL"
# ↑ --------------------------
# `jekyll-seo-tag` 设置的结尾

google_analytics:
  id: # fill in your Google Analytics ID

# 首选配色方案设置。
#
# 注意：默认情况下，保持为空将遵循系统首选颜色、
# 在侧边栏左下方会有一个在深色和浅色之间切换主题的开关。
# 在侧边栏左下方。
#
# 可用选项：
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# 图像的 CDN 端点。
# 请注意，一旦分配了它，CDN 网址
# 将被添加到所有以"/"开头的图片（网站头像和文章图片）路径中。
#
# e.g. 'https://cdn.com'
img_cdn:

# 侧边栏上的头像，支持本地或 CORS 资源
# avatar: 'https://fastly.jsdelivr.net/gh/XiaoWendell/img_note@empty/1676013834932188d1c5a-bee0-40e6-a0a6-2973e0f343b0.jpg'
# https://raw.githubusercontent.com/用户名/项目名称/master/图片文件夹/xxx.png
# avatar: '{{site.baseurl}}/assets/img/myimg/about-HJ.jpg'
# avatar: 'https://raw.githubusercontent.com/XiaoWendell/XiaoWendell.github.io/assets/img/myimg/about-HJ.jpg'
# avatar: 'https://github.com/XiaoWendell/XiaoWendell.github.io/assets/img/myimg/about-HJ.jpg'
avatar: 'assets/img/avatar/avatar.jpg'

# 布尔类型，是帖子中 TOC 的全局开关。
toc: true

comments:
  active: 'giscus'        # 用于帖子评论的全局开关，例如 “disqus”。 留空表示禁用
  # 激活的选项如下
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus 选项 ' https://giscus.app
  giscus:
    repo: "XiaoWendell/XiaoWendell.github.io"           # <gh-username>/<repo>
    repo_id: "R_kgDOKhSzCA"
    category: "General"
    category_id: "DIC_kwDOKhSzCM4CaNBa"
    mapping: "title"          # optional, default to 'pathname'
    input_position: "top"   # optional, default to 'bottom'
    lang: "zh-CN"             # optional, default to the value of `site.lang`
    reactions_enabled: "1" # optional, default to the value of `1`

    # 我添加的部分
    strict: "0"
    emit-metadata: "0"
    loading: "lazy"
    crossorigin: "anonymous"

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# 网站的基本 URL
baseurl: ""

# ------------ 以下选项不建议修改 ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 这里的空字符串表示项目中的所有文件
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.

      # 除非您有足够的信心，否则切勿修改以下参数
      # 更新本项目中所有其他帖子链接的代码。
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json
  - 'local_checker.bat'
  - 'local_start.bat'
  - 'ruby_cmd.bat'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
